### ISSUE TITLE
如何默认推H264

### ISSUE THREAD

**Issue by zkevindev** [scaret/whip-whep-node-webrtc#1]
测试send.js时发现默认推VP8，我想推h264，然后转到其他协议输出

**Comment by scaret** [comment]
取决于服务端返回的Answer。如果你使用了demo中提供的基于node-webrtc的服务端的话，需要重新编译node-webrtc，并在answer中把h264之前的编码删掉

https://github.com/node-webrtc/node-webrtc/issues/431
